### PR TITLE
`debpack` suppport

### PR DESCRIPTION
**Pull request by zmarffy**
Hey, it's very hard to test on my end as my setup doesn't have a display, but the code seems to be synactically correct, at least. Try this out. This should allow `debpack` to be run for the source code of this repo. Check out the code changes and files I added added.

The idea is to move the main file to `/usr/bin/` and the supporting files to another location. New code I wrote helps import those files from the other location. You need a new requirement though for the program, `zmtools`. I added it to `requirements.txt`. Make sure you install that!

### CODE REVIEW

**Comment by zmarffy** [comment]
While you're at it, make sure you update `debpacker`. You actually helped me uncover a bug.

**Comment by NeonCrafter13** [comment]
I created a new pull request from your Repository because i wanted to have the debpack stuff on a diffrent branch

**Comment by zmarffy** [comment]
Sounds good to me, but note that DEB files should not be checked into git. Make sure you remove the file before merging it with the main branch.

**Comment by NeonCrafter13** [comment]
That was a mistake tommorow I will fix it.

**Pull request closed without merging**
